# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameround_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameround',
            name='test',
        ),
        migrations.AlterField(
            model_name='gameroundusertask',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 22, 21, 45, 201024, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
