# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160822_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakeuser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='last_name',
            field=models.CharField(default='G', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameplan',
            name='fake_user_count',
            field=models.IntegerField(default=0),
        ),
    ]
