# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160823_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeuser',
            name='game_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.GameRound'),
            preserve_default=False,
        ),
    ]
