# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20160904_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questionchoices',
            name='answer_text',
            field=models.CharField(max_length=400),
        ),
    ]
