# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20160904_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionchoices',
            old_name='answer_text',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='questionchoices',
            old_name='correct_answer',
            new_name='correct_choice',
        ),
        migrations.AddField(
            model_name='questionchoices',
            name='choice_code',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
