# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20160904_1338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionChoices',
            new_name='QuestionChoice',
        ),
    ]
