# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20160904_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoundTaskQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_sequence', models.IntegerField()),
                ('game_round_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameRoundTask')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Question')),
            ],
        ),
    ]
