# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 16:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_gameroundtaskquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplantask',
            old_name='user_defined_dim',
            new_name='user_defined_brightness',
        ),
        migrations.RemoveField(
            model_name='gameplantask',
            name='dim_percent',
        ),
        migrations.RemoveField(
            model_name='gameroundusertask',
            name='dim_percent',
        ),
        migrations.AddField(
            model_name='gameplantask',
            name='brightness',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='gameroundusertask',
            name='brightness',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
