# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20160912_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='first_place_game_round_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameRoundUser'),
        ),
    ]
