# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0018_gameround_winning_game_round_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamerounduser',
            name='privacy_choice',
            field=models.CharField(choices=[('P', 'Private'), ('B', 'Building'), ('R', 'Room')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
