# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20160913_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='allow_fake_users_to_win',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
