# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_gameround_allow_fake_users_to_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerounduser',
            name='privacy_choice',
            field=models.CharField(blank=True, choices=[('P', 'Private'), ('B', 'Building'), ('R', 'Room')], max_length=1, null=True),
        ),
    ]
