# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20160914_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_level', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='gamerounduser',
            name='privacy_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.PrivacyChoice'),
        ),
    ]
