# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20160914_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacychoice',
            name='sequence',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
