# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_privacychoice_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='first_place_game_round_user',
        ),
        migrations.AddField(
            model_name='winner',
            name='game_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameRound'),
        ),
        migrations.AddField(
            model_name='winner',
            name='game_round_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameRoundUser'),
        ),
    ]
