# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_gameround_number_of_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeuser',
            name='building',
            field=models.CharField(default='Cory', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='room',
            field=models.CharField(default='406', max_length=50),
            preserve_default=False,
        ),
    ]
